const MENU_SUCCESS_OPTIONS = 'MENU_SUCCESS_OPTIONS'
const MENU_OPTIONS_FAIL = 'MENU_OPTIONS_FAIL'
const MENU_OPTIONS = 'MENU_OPTIONS'

export { MENU_SUCCESS_OPTIONS, MENU_OPTIONS_FAIL, MENU_OPTIONS }
